name: Research
description: Investigating, exploring, or evaluating new concepts, tools, or technologies.
labels:
  - research
projects:
  - Ofadiman/6
assignees:
  - Ofadiman
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: Purpose
      description: Clearly outline the purpose of the research, including the problem or topic being investigated, and the expected outcome or goal.
      placeholder: |
        There are many platforms on the market that provide hosting services for web applications. To deploy the application to the production environment, we need to choose one of the hosting platforms. We need to conduct research on the pricing of selected services and their hosting capabilities (e.g. whether they also provide database hosting solutions).

  - type: textarea
    attributes:
      label: Technical Requirements and Implementation Details
      description: Describe the technical requirements that must be considered for completing the task. If applicable, include implementation details that should be followed while completing the task.
      placeholder: |
        - Dependencies should be updated using the current package manager.
        - The chosen solution should allow to deploy applications in containers.
        - The database password should be saved in the project secrets.

  - type: textarea
    attributes:
      label: Business Requirements
      description: Describe the business requirements that must be considered for completing the task.
      placeholder: |
        - Integration with the advertising service is retained in its current form.
        - The total monthly cost of running the application should not exceed $100.

  - type: textarea
    attributes:
      label: Resources
      description: List any relevant resources, such as documentation, tutorials, or external links, that might be helpful in completing the task.
      placeholder: |
        - [AWS pricing calculator.](https://calculator.aws/)
        - [Documentation of the docusaurus tool.](https://docusaurus.io/)
        - [MaterialUI library documentation.](https://mui.com/material-ui/)
        - [Railway service pricing.](https://railway.app/pricing)
        - [Using secrets in GitHub Actions.](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions)

  - type: textarea
    validations:
      required: true
    attributes:
      label: Acceptance Criteria
      description: Specify the conditions that must be met for the task to be considered complete and satisfactory.
      placeholder: |
        - [ ] 1 platform is selected on which the application will be deployed.
        - [ ] Dependencies are updated to the latest versions.
        - [ ] E2E tests check whether a user can log in and out.
        - [ ] Technical documentation contains a section on possible options for deploying the application to a production environment.
        - [ ] The account registration form is displayed on the `/auth/sign-in` page.
        - [ ] The documentation contains information about adding a file containing database migrations.
        - [ ] The documentation contains information about running migrations on a local, staging and production databases.
        - [ ] When CI/CD pipeline fails, a notification is sent to slack.
