name: Tests
description: Changes to current automated tests or adding new tests.
labels:
  - test
projects:
  - Ofadiman/6
assignees:
  - Ofadiman
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: Description
      description: Describe which parts of the code have missing tests.
      placeholder: |
        The module related to user account management has no E2E testing at all.

  - type: textarea
    attributes:
      label: Technical Requirements and Implementation Details
      description: Describe the technical requirements that must be considered for completing the task. If applicable, include implementation details that should be followed while completing the task.
      placeholder: |
        - Dependencies should be updated using the current package manager.
        - The chosen solution should allow to deploy applications in containers.
        - The database password should be saved in the project secrets.

  - type: textarea
    attributes:
      label: Resources
      description: List any relevant resources, such as documentation, tutorials, or external links, that might be helpful in completing the task.
      placeholder: |
        - [AWS pricing calculator.](https://calculator.aws/)
        - [Documentation of the docusaurus tool.](https://docusaurus.io/)
        - [MaterialUI library documentation.](https://mui.com/material-ui/)
        - [Railway service pricing.](https://railway.app/pricing)
        - [Using secrets in GitHub Actions.](https://docs.github.com/en/actions/security-guides/using-secrets-in-github-actions)

  - type: textarea
    validations:
      required: true
    attributes:
      label: Acceptance Criteria
      description: Specify the conditions that must be met for the task to be considered complete and satisfactory.
      placeholder: |
        - [ ] 1 platform is selected on which the application will be deployed.
        - [ ] Dependencies are updated to the latest versions.
        - [ ] E2E tests check whether a user can log in and out.
        - [ ] Technical documentation contains a section on possible options for deploying the application to a production environment.
        - [ ] The account registration form is displayed on the `/auth/sign-in` page.
        - [ ] The documentation contains information about adding a file containing database migrations.
        - [ ] The documentation contains information about running migrations on a local, staging and production databases.
        - [ ] When CI/CD pipeline fails, a notification is sent to slack.
